// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/health-check": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/health-check";
  };
  "routes/common/kortz.tsx": {
    id: "routes/common/kortz";
    page: "/";
  };
  "routes/common/health-check.tsx": {
    id: "routes/common/health-check";
    page: "/health-check";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/common/kortz": typeof import("./app/routes/common/kortz.tsx");
  "routes/common/health-check": typeof import("./app/routes/common/health-check.tsx");
};